name: bbb
version: 16-0.1
summary: Beagle Bone Black
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image for the Beaglebone Black.
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable

parts:
  uboot:
    plugin: make
    source: git://git.denx.de/u-boot.git
    source-branch: v2017.01
    artifacts: [MLO, u-boot.img]
    prepare: |
      git apply ../../../uboot.patch
      make am335x_boneblack_config
    install: |
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      cd $SNAPCRAFT_PART_INSTALL/; ln -s uboot.env uboot.conf
    build-packages:
      - libpython2.7-dev
      - build-essential
      - bc

slots:
  gpio-20:
    interface: gpio
    number: 20
  gpio-26:
    interface: gpio
    number: 26
  gpio-27:
    interface: gpio
    number: 27
  gpio-44:
    interface: gpio
    number: 44
  gpio-45:
    interface: gpio
    number: 45
  gpio-46:
    interface: gpio
    number: 46
  gpio-47:
    interface: gpio
    number: 47
  gpio-48:
    interface: gpio
    number: 48
  gpio-49:
    interface: gpio
    number: 49
  gpio-60:
    interface: gpio
    number: 60
  gpio-61:
    interface: gpio
    number: 61
  gpio-65:
    interface: gpio
    number: 65
  gpio-66:
    interface: gpio
    number: 66
  gpio-67:
    interface: gpio
    number: 67
  gpio-68:
    interface: gpio
    number: 68
  gpio-69:
    interface: gpio
    number: 69
  gpio-112:
    interface: gpio
    number: 112
  gpio-115:
    interface: gpio
    number: 115
  gpio-117:
    interface: gpio
    number: 117
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
